packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
  sharp: true
overrides:
  '@prisma/config>deepmerge-ts': 8.0.0
  'prisma>mysql2': 3.23.1
